afroquotes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.AllQuotes.as_view(), name="index"),
    path("upvote", views.upvote, name="upvote"),
    path("auth/login", views.UserAuth.as_view(), name="login"),
   
    path('auth/register', views.CreateUserAPIView.as_view(), name='register'),
    path("logout", views.logout_view, name="logout"),
    path("submitquote", views.SubmitQuoteClass.as_view(), name="submitQuote"),
    path("search", views.search, name="search"),
    path("user", views.UserProfile.as_view(), name="view_user_profile"),
    path("user/editbio", views.UserProfile.as_view(), name="editbio"),
    path("annotate", views.Annotate.as_view(), name="annotate"),

]

quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("afroquotes.urls")),
    path('djrichtextfield/', include('djrichtextfield.urls'))
]

afroquotes/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime    
from djrichtextfield.models import RichTextField
from djongo import models as mongo_models
import random 

# Create your models here.
default_usernames= ["Amina1","Kwame4","Imani7","Sade92","Jelani5","Fatou3","Chuma8","NiaBee","Tafari","ZolaK9"]
class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    # def create_superuser(self, email, password, **extra_fields):
    #     user = self.create_user(
    #             email=self.normalize_email(email),
    #         )
    #     user.is_admin = True
    #     user.is_staff = True
    #     user.is_superuser = True
    #     user.set_password(password)
    #     user.save(using=self._db)

class User(AbstractBaseUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=20, default=random.choice(default_usernames))
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    bio = models.CharField(max_length=256, null=True)
    profile_image= models.URLField(null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    def get_annotation_iq(self):
        contributed_annotation = Annotation.objects.filter(annotator=self)
        annotation_iq=0
        if contributed_annotation:

          for annotation in contributed_annotation:
              upvote_count = annotation.get_upvotes()
              annotation_iq += upvote_count
        return annotation_iq

    def get_annotations(self):
        return Annotation.objects.filter(annotator=self).values("annotated")


class Quote(models.Model):
    quote=models.CharField(max_length=500)
    artist=models.CharField(max_length=64)
    song=models.CharField(max_length=64, null=True)
    image= models.URLField()
    contributor= models.ForeignKey(User, on_delete=models.DO_NOTHING)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)
    # approved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quote} {self.song} {self.artist}"

    def serialize(self):
        return{
            "id": self.id,
            "quote":self.quote,
            "image":self.image,
            "song": self.song,
            "contributor":self.contributor.username,
            "artist":self.artist,
            "date":self.timestamp.strftime("%A, %d. %B %d/%m/%Y %I:%M%p"),
            "annotation":self.quote_annotation()
        }

    def quote_annotation(self):
        annotation = Annotation.objects.filter(annotated=self)
        if annotation:
            return annotation[0].serialize()
        else:
            return None

    
class Annotation(models.Model):
    annotation=models.CharField(max_length=300)
    annotator=models.ForeignKey(User, on_delete=models.DO_NOTHING)
    annotated=models.ForeignKey(Quote, on_delete=models.DO_NOTHING)
    verified= models.BooleanField(default=False)
    annotation_view_count=models.IntegerField(null=True, default=0)
    last_viewed=models.DateTimeField(null=True)
    timestamp = models.DateTimeField(default=datetime.now)
    approvers = models.ManyToManyField(User, related_name="approvers")

    def serialize(self):
        return{
            "id":self.id,
            "annotation":self.annotation,
            "annotated_quote": self.annotated.quote,
            "annotated_quote_song": self.annotated.song,
            "annotated_quote_image": self.annotated.image,
            "annotated_quote_artist": self.annotated.artist,
            "annotated_quote_contrib": self.annotated.contributor.username,
            "annotated_quote_id": self.annotated.id,
            "annotated_quote_timestamp": self.annotated.timestamp.strftime("%A, %d. %B %d/%m/%Y %I:%M%p"),
            "annotator": self.annotator.username,
            "annotation_view_count":self.annotation_view_count,
            "last_viewed":self.last_viewed.strftime("%A, %d. %B %d/%m/%Y %I:%M%p") if self.last_viewed else None,
            "upvotes": self.upvotes.count() if self.upvotes else 0,
            "comments": self.get_comments(),
            "verified":self.verified,
        }


    def check_veracity(self):
        if self.approvers.count() >= 2 and self.annotator not in [approver for approver in self.approvers.all()]:
            self.verified = True
            self.save()

    def get_upvotes(self):
        return self.upvotes.count() 
    def get_user_upvote(self, user_id):
        return True if Upvote.objects.filter(user=user_id, annotation=self.id) else False
    def get_comments(self):
        comments= SuggestionComment.objects.filter(annotation=self)
        return [comment.serialize() for comment in comments]


class Upvote(models.Model):
    annotation = models.ForeignKey(Annotation, on_delete=models.CASCADE, related_name="upvotes")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="upvoted")
    timestamp = models.DateTimeField(auto_now_add=True)

class SuggestionComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_suggestion")
    annotation= models.ForeignKey(Annotation, on_delete=models.CASCADE, related_name="comments")
    suggestion = models.CharField(max_length=300)

    def serialize(self):
        return{

        "id": self.id,
        "user": self.user.username,
        # "annotation": self.annotation.serialize(),
        "annotation_id": self.annotation.id,
        "suggestion": self.suggestion

        }

afroquotes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django import forms
import json
import datetime
import time
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import JsonResponse
from rest_framework.authtoken.views import ObtainAuthToken
from django.contrib.auth import get_user_model
from rest_framework.generics import CreateAPIView
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny, IsAuthenticated
from django.views import View
from rest_framework.authtoken.models import Token
from djrichtextfield.widgets import RichTextWidget
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.exceptions import ValidationError, APIException
from rest_framework.response import Response
from rest_framework import status
from .youtube_charts import search_youtube
# from mongo_utils import get_db_handle
from bson.objectid import ObjectId
from .models import *
# from .nonrel_model import *
from . import config
from .serializers import *
import logging


logger = logging.getLogger(__name__)

# Create your views here.
class SubmitQuoteForm(forms.Form):
    quote = forms.CharField(widget=forms.Textarea())
    song = forms.CharField(max_length=64)
    artist= forms.CharField(max_length=64)
    image = forms.URLField()
    quote_id = forms.CharField(required=False)

class SubmitQuotePatch(forms.Form):
    quote_id = forms.IntegerField()

class AnnotateForm(forms.Form):
    annotation=forms.CharField(max_length=300)
class searchForm(forms.Form):
    queryTerm= forms.CharField(max_length=32)
class SuggestImprove(forms.Form):
    comment = forms.CharField(min_length=32, max_length=300)


def index(request):
    quotes = Quote.objects.all()
    return render(request, "afroquotes/googleindex.html", {"quotes":quotes})


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "afroquotes/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "afroquotes/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "afroquotes/register.html")

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "afroquotes/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "afroquotes/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

class CreateUserAPIView(CreateAPIView):
    serializer_class = CreateUserSerializer
    permission_classes = [AllowAny]

    def create(self, request, *args, **kwargs):
        logging.info(f"CreateUserAPIView, create user request: {request}")
        logging.info(f"CreateUserAPIView, create user form data: {request.data}")
        serializer = self.get_serializer(data = request.data)
        ex = serializer.is_valid(raise_exception=True)
        logging.info(f"CreateUserAPIView CreateRequest for user {request.data}")
        try:
            user = self.perform_create(serializer)
            headers = self.get_success_headers(serializer.data)
           
            logging.info(user)
            return Response(
                    {**serializer.data}
                )
        
        except ValueError as ex:
            logging.error(f"CreateUserAPIView ValueError: {ex} ")
            # logger.warning(f"CreateUserAPIView ValueError: {ex} ")
            print(f"CreateUserAPIView serializers.ValidationError: {ex} ")
            return JsonResponse({"error":str(ex)})
            
        except serializers.ValidationError as err:
            logging.error(f"CreateUserAPIView serializers.ValidationError: {err} ")
            # logger.warning(f"CreateUserAPIView serializers.ValidationError: {err} ")
            print(f"CreateUserAPIView serializers.ValidationError: {err} ")
            
            return JsonResponse({"error":str(err)})
        except Exception as ex:
            print(f"PRINT    CreateUserAPIView serializers.ValidationError ")
            logging.exception(f"CreateUserAPIView Exception: {ex} ")
        return Response(ex)


class UserAuth(ObtainAuthToken):
    """
    Serves request to authenticate a app user 
    sub-classing the ObtainAuthtoken rest-framework auth class
    """
    # serializer_class = UserSerializer
    permission_classes = [AllowAny]

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data,
                                           context={'request': request})

        try:
            serializer.is_valid(raise_exception=True)
            user = serializer.validated_data['user']
            logging.info(f"UserAuth Login request for user {user.email}")
            logging.info(f"UserAuth Login request for user {user.email}")
            
            token, created = Token.objects.get_or_create(user=user)
            user = UserSerializer(user)
            logger.info({
                'token': token.key,
                'user': user.data
            })
            return Response({
                'token': token.key,
                'user': user.data
            })
        except ValidationError as err:
            logging.info(f"UserAuthr: {err} ")
            logging.error("UserAuth Error")
            return Response({"Error":str(err)}, status=401)
        except Exception as ex:
            return JsonResponse({"Error": str(ex)}, safe=False, status=400)

class AllQuotes(APIView):
    permission_classes = [AllowAny]
    serializer_class = QResponseSerializer
    def get(self, request):
        session = request.user
        logger.info(f"SESSION: {session}")
        query_term = request.GET.get('q')
        page_num = request.GET.get('page', 1)
        logger.info(f"CURR_PAGE_NUM:  {page_num}")
        if request.session.get('data'):
            quotes = request.session.get('data')
            logger.info("SESSION_DATA")
        else:
            quotes = get_all_quotes(query=query_term)
            quotes = QResponseSerializer(map(lambda quote: quote.serialize(), list(quotes)), many=True)
            quotes = quotes.data
            request.session['data'] = quotes
            logger.info("NO_SESSION_DATA")

        context = custom_pagination(request, quotes, page_num, per_page=50)

        return Response(context)
        # return render(request, 'afroquotes/index.html', context)

class Annotate(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = SubmitAnnotation
    def put(self, request):
        request_user = request.user
        logger.info(f"USER SUBMITTING ANNOTATION, {request_user}")
        serializer = SubmitAnnotation(request.data)
        logger.info(f"ANNOTATION data, {serializer.data}")
        annotator = User.objects.get(id=serializer.data.get("annotator"))
        if annotator != request_user:
            return Response({"message":"Unauthrized user action"}, status=500)
        quote = Quote.objects.get(id=serializer.data.get("annotated"))

        annotation = Annotation(annotator=annotator, annotated=quote, annotation=serializer.data.get("annotation"))
        annotation.save()

        context = QResponseSerializer(quote.serialize())
        return Response({**context.data})


    
# @csrf_exempt
@api_view(["GET","POST"])
def search(request):
    query = request.GET.get('q', '')
    print(query)
    quotes= Quote.objects.filter(quote__icontains=query) | Quote.objects.filter(song__icontains=query) | Quote.objects.filter(artist__icontains=query)
    print(quotes)
    if len(quotes)>0:
        # handle empty querySet here return not found error
        # quotes = Quote.objects.all().order_by("-timestamp")
        page_num = request.GET.get('page')
        paginator = Paginator(quotes, 5)
        try:
            page_obj= paginator.get_page(page_num)

        except PageNotAnInteger:
            page_obj= {'error', 'Invalid Page'}

        except EmptyPage:
            page_obj = paginator.get_page(1)


        if page_obj.has_next():
            page_obj_next = page_obj.next_page_number()
        else:
            page_obj_next = 1

        if page_obj.has_previous():
            page_obj_prev = page_obj.previous_page_number()
        else:
            page_obj_prev = 1
        
        total_pages = paginator.num_pages
        links = {'next': page_obj_next, 'prev':page_obj_prev}

        # Here I map a lambda function over the queryset of Models to 
        # return the dictionary representation for each element in the list
       
        quotes =  QResponseSerializer(map(lambda quote: quote.serialize(), list(quotes)), many=True)
    

afroquotes/templates/afroquotes/annotation.html
{% extends "afroquotes/layout.html" %}



    {% block body %}
    <section class="showcase">
    <div class="col-lg-4">
        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <img class="img-fluid rounded-circle mb-3" src="{{quote.image}}">
        </div>
    </div>
    <div class="container-fluid p-0">
        <div class="row no-gutters">
            <div class="col-lg-6 order-lg-1 my-auto showcase-text shadow-sm p-3 mb-5 bg-body rounded" style="background-image: url'({{quote.image}});">
                <h2>{{quote.song}}</h2>
                <h5>{{quote.artist}}</h5>
                <blockquote class="blockquote">
                    <mark>{{quote.quote}}</mark>
                    <p class="lead mb-0"></p>
                </blockquote>
            </div>
            
            <div class="col-lg-6 order-lg-2">
                <form method="POST" action="{% url 'write_annotate' quote.id %}">
                    {% csrf_token %}
                    <div class="card border-primary rounded-0">
                        <div class="card-header p-0">
                            <div class="bg-info text-white text-center py-2">
                                <h3><i class="fa fa-comment text-info"></i> Write Annotation</h3>
                                <p class="m-0">Please stay objective. No restriction on litrary style.</p>
                            </div>
                        </div>
                        <div class="card-body p-3">
                            <!--Body-->
                            <div class="form-group">
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="fa fa-user text-info"></i></div>
                                    </div>
                                    <input type="text" class="form-control" id="username" name="username" placeholder="{{user.username}}" readonly>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="fa fa-envelope text-info"></i></div>
                                    </div>
                                    <input type="email" class="form-control" id="email" name="email" placeholder="{{user.email}}" readonly>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group mb-2">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"><i class="fa fa-comment text-info"></i></div>
                                    </div>

                                    <textarea class="form-control" name="annotation" id="id_annotation" placeholder="Annotate..." required></textarea>

                                </div>
                            </div>
                            <div class="text-center">
                                <input type="submit" value="submit" class="btn btn-info btn-block rounded-0 py-2">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!--  If annotation not found block -->
            {% if notfoundError %}
            <div class="col-lg-6 order-lg-2 showcase-text">
                <h4>No Annotation Found</h4>
                <p class="lead mb-0">{{notfoundError}}<a href="{% url 'write_annotate' quote.id %}">Annotate</a></p>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endif %}
<!-- More Quotes from "Song" -->
{% if sQuotes %}
<section class="testimonials bg-light text-center">
    <div class="container">
        <h2 class=mb-5> More Quotes from "{{quote.song}}"</h2>
        <div class="row">
            <div class="col-lg-4">
                {% for quote in sQuotes%}
                {{quote}}
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endif %}
<!-- End More Quotes from "Song" -->
<!-- More Quotes by "artist" -->
{% if aQuotes %}
<section class="testimonials bg-light text-center">
    <div class="container">
        <h2 class=mb-5> More Quotes by "{{quote.artist}}"</h2>
        <div class="row">
            <div class="col-lg-4">
                {% for quote in aQuotes%}
                {{quote}}
                {% endfor %}
            </div>
        </div>
    </div>
</section>
<!-- End More Quotes by "artist" -->
{% endif %}
    {% endblock %}

afroquotes/templates/afroquotes/charts.html
{% extends "afroquotes/layout.html" %}
{% load static %}
{% block body %}
{% if message %}
{{message}}
{% endif %}
    <div class="container-fluid gedf-wrapper">
        {% if slug %}
        <h1 class="h1">{{slug}} CHARTS</h1>
        {% endif %}
        <div class="row">
            <div class="col-sm-12 col-md-8 gedf-main">
                {% for annotation in annotations %}

                <div class="card gedf-card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="mr-2">
                                    <img class="rounded-circle" width="60" src="{{annotation.annotated_quote_image}}" alt="">
                                </div>
                                <div class="ml-2">
                                    <div class="h5 m-0">{{annotation.annotated_quote_artist}}</div>
                                    <div class="h7 text-muted">{{annotation.annotated_quote_song}}</div>
                                </div>
                            </div>
                            <div>
                                <div class="dropdown">
                                    <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-ellipsis-h"></i>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                                        <div class="h6 dropdown-header">Configuration</div>
                                        <a class="dropdown-item" href="#">Save</a>
                                        <a class="dropdown-item" href="#">Hide</a>
                                        <a class="dropdown-item" href="#">Report</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="card-body">
                        <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>{{annotation.annotated_quote_timestamp}}</div>
                        <a class="card-link" href="#">
                            <h5 class="card-title">{{annotation.annotated_quote}}</h5>
                        </a>

                        <p class="card-text">
                            
                        </p>
                    </div>
                    <div class="card-footer">
                        <i class="fa fa-solid fa-eye view-count">
                            {{annotation.annotation_view_count}}
                        </i>
                        <button class="card-link view-annotation" type="button" aria-expanded="false" aria-controls="" data-toggle="collapse" data-clicked="false" data-link="{{annotation.id}}" data-target="#quote_{{annotation.annotated_quote_id}}"><i class="fa fa-comment"></i> See annotation </button>
                        <a href="{% url 'view_on_yt' annotation.annotated_quote_id %}" target="_blank" class="card-link"><i class="fa fa-mail-forward"></i> Listen Now</a>
                    </div>
                    <div class="collapse" id="quote_{{annotation.annotated_quote_id}}" data-link="{{annotation.id}}">
                          <div class="card card-body">
                           {% if annotation.annotation %}
                           <div class="h7 text-muted">annotated by: {{annotation.annotator}}</div>
                            <div>
                           <a class="card-link upvote" data-link="{{annotation.id}}"><i class="fa fa-solid fa-circle-up">{{annotation.upvotes}}</i>
                              </a>
                          </div>
                           {{annotation.annotation}}
                           {% else %}
                           There's no annotation for this quote yet.
                           {% endif %}
                          </div>
                          <div class="collapse" id="annotate_{{quote.annotation.id}}" data-link="annotate_{{quote.annotation.id}}">
                              <div class="card card-body">
                                 {% if form.annotation.errors %}
                                 Annotation Field Error: {{ form.annotation.errors }}
                                 {% endif %}
                                 
                              </div>
                           </div>
                          {% if annotation.annotation %}
                           
                           <div class="search col-10">
                           <input placeholder="Suggest annotation improvement" type="text">
                           <button type="button" class="btn btn-primary">submit</button>
                          </div>
                           {% endif %}
                     </div>
                </div>
                {% endfor %}
                <!-- Post /////-->

            </div>
            <div class="col-sm-6 col-md-4">
                <div class="card gedf-card">
                    <div class="card-body">
                        <h5 class="card-title">Latest </h5>
                        <h6 class="card-subtitle mb-2 text-muted"></h6>
                        <p class="card-text">These are the top viewed and shared quotes of all time.</p>
                        <a href="/" class="card-link">View</a>
                    
                    </div>
                </div>
                <div class="card gedf-card">
                        <div class="card-body">
                            <h5 class="card-title">Top 10 Weekly</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Week: </h6>
                            <p class="card-text">These are the top viewed, shared quotesa nd annotations this week.</p>
                            <a href="#" class="card-link">View</a>
                            
                        </div>
                    </div>
            </div>
            
        </div>
    </div>

    <!-- <script type="text/javascript">
       $('.collapse').collapse()
    </script> -->
{% endblock %}

afroquotes/templates/afroquotes/index_js.html
{% extends "afroquotes/layout.html" %}

{% block body %}
  <section class="showcase ">
    <div class="container-fluid">
      <div class="row no-gutters justify-content-center">
        <div id="q_block" class="">
          
        </div>

        <!-- <div class="col-lg-6  my-auto showcase-text shadow-sm p-3 mb-5 bg-body rounded">
          <div class="">
          </div>
        </div> -->
      </div>
    </div>
  </section>
{% endblock %}

<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        View Comments
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
</div>

afroquotes/templates/afroquotes/register.html
{% extends "afroquotes/layout.html" %}

{% block body %}

    <h2>Sign Up</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Sign Up">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}